#server.port=8002
#user.userServiceUrl=http://localhost:8001/
server:
  port: 8002
spring:
  application:
    name: ms-consumer-sample
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

ms-provider-sample:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule